Fixing iRODS functionality - issue #1510
snakemake/snakemake pull request #1611
Opened 2022-04-27 22:59 UTC by ScottMastro

### Description

This PR includes my recommended changes suggested on issue #1510
- This brings the functionality of this remote module in-line with what the documentation says (specifically, that the "zone" is not needed in the path). 
- This also fixes an issue where the module does not work unless an iRODS user has read access to all directories in the path. This fix avoids throwing an error if a user doesn't have read access to one or more superdirectories.
  
### QC

* [ x ] The PR contains a test case for the changes or the changes are already covered by an existing test case.
* [ x ] The documentation (`docs/`) is updated to reflect the changes or this is not necessary (e.g. if the change does neither modify the language nor the behavior or functionalities of Snakemake).

2022-05-02 11:30 UTC, johanneskoester requested changes

2022-05-02 11:30 UTC, johanneskoester commented on snakemake/remote/iRODS.py
> +            print(collpath)
```suggestion
```

2022-05-09 22:14 UTC, ScottMastro commented
The irods test was failing because an exception was being thrown when checking for access to a subdirectory that doesn't exist yet - this should be handled now.

2022-05-16 10:10 UTC, johanneskoester approved these changes

2022-05-16 10:11 UTC, merged