Attempt to fix storage plugin bug on Windows
snakemake/snakemake pull request #2487
Opened 2023-10-20 15:51 UTC by melund

### Description

This PR attempts to fix the storage bug plugin test failures on Windows. 

@johanneskoester, I am not sure this is how you want to fix the bug, but it should give you an idea what the problem is. 

Basically, on Windows all files in rules etc. are converted to forward slashes to avoid the 'backslash' mesh. However, the new storage plugin was calling using 'pathlib' internally. Converting pathlib.Path objects to strings gives paths with 'backslash'es on Windows. 

Fixes: #2473

### QC

* [x] The PR contains a test case for the changes or the changes are already covered by an existing test case.
* [x] The documentation (`docs/`) is updated to reflect the changes or this is not necessary (e.g. if the change does neither modify the language nor the behavior or functionalities of Snakemake).

2023-10-21 06:22 UTC, melund commented on .gitattributes
> +* text=auto eol=lf
This ensures files are checked-out with linux file endings on Windows.That is usually not the recommendation for windows. But this is the best option given how many input-output files in the tests system that are manipulated by posix tools.

2023-10-21 06:26 UTC, melund commented on pytest.ini
> +python_files = tests/tests.py tests/test_expand.py tests/test_io.py tests/test_schema.py tests/test_linting.py tests/test_executor_test_suite.py
The test suite contains plenty of files which doesn't follow the standard pytest conventions. This tripped the vs-code test plugin which tried to inspect non-test files which it thought caused it to crash.

2023-10-21 11:50 UTC, melund commented
@johanneskoester. Test pass and it is ready for review.

2023-10-30 12:59 UTC, johanneskoester requested changes
Thanks a lot! Sorry, the review was done since last week, but I forgot to hit the submit button. One thing below.

2023-10-31 19:26 UTC, melund commented on snakemake/io.py
> +            file_with_wildcards_applied = IOFile(local_path_str, rule=self.rule)
@johanneskoester, and have done that and pushed a new version.

2023-11-13 10:52 UTC, johanneskoester commented
Seems like touching directories on windows does not work anymore with the changes here.

2023-11-14 07:17 UTC, melund commented
> Seems like touching directories on windows does not work anymore with the changes here.

I will try to roll back so the check doesn't happen inside IOFile. The test were able to pass before I did that.

2023-11-21 18:32 UTC, johanneskoester requested changes

2023-11-21 18:32 UTC, johanneskoester commented on snakemake/io.py
> +            file_with_wildcards_applied = IOFile(local_path_str, rule=self.rule)
The Path object has a method `as_posix()` which does exactly what you do here. I don't understand though why we need this at all. What is the problem with having a windows path returned here?

2023-11-21 20:23 UTC, johanneskoester commented
I have now implemented a simpler version of this in #2519. Thanks a lot for this work here, which pointer me to the right places for a simplified fix!

2023-11-21 20:23 UTC, closed without merging