feat: add extra info on benchmark file
snakemake/snakemake pull request #2691
Opened 2024-02-10 19:12 UTC by fgvieira

### Description

Another try at #2176, trying to keep it more general by just adding extra info to the benchmark file. The idea is to gather information about a job, not only resources used, but also resources requested.

Some questions:
- is `benchmark` file the best place to have all this info?
- is there any unnecessary info (e.g. jobid)?
- are we missing any important info?
- is a `tsv` the best format? If not, maybe `json`?

@SichongP @corneliusroemer feel free to comment.

### QC

* [ ] The PR contains a test case for the changes or the changes are already covered by an existing test case.
* [ ] The documentation (`docs/`) is updated to reflect the changes or this is not necessary (e.g. if the change does neither modify the language nor the behavior or functionalities of Snakemake).

2024-02-10 21:31 UTC, SichongP commented
Is this a replacement of my PR? Sorry I haven't looked much into it. Just want to know if I still need to refactor my PR to the new format (I should have some more time to work on it in the next two weeks)

2024-02-10 22:09 UTC, fgvieira commented
Not sure... I started it just to explore a simpler way to do it (just adding more info to the `benchmark` file), but I don't know if this is the best way to go (hence all the questions).

2024-04-18 20:47 UTC, johanneskoester requested changes
Great work!

2024-04-19 07:07 UTC, fgvieira commented on docs/snakefiles/rules.rst
> +* `cpu_usages`: Total CPU time (seconds),
Those values are collected by `benchmarks` and I have not added any new, but `cpu_time` is the total user+system time, while `cpu_usage` seemd to be the CPU load on a period of time.

https://github.com/snakemake/snakemake/blob/f55801bfabfb916f77fa4ec8f9eb0667e5c8a92e/snakemake/benchmark.py#L231-L234

2024-04-24 13:11 UTC, johanneskoester approved these changes

2024-04-24 13:13 UTC, johanneskoester commented on docs/snakefiles/rules.rst
> +* `cpu_usages`: Total CPU time (seconds),
Ok, but shouldn"t this then be called cpu_usage and not cpu_usages?

2024-04-24 19:36 UTC, fgvieira commented on docs/snakefiles/rules.rst
> +* `cpu_usages`: Total CPU time (seconds),
sure, I can change it.

2024-04-24 19:54 UTC, merged