add snakemake and reportplugins to req.txt to build docs
snakemake/snakemake pull request #2817
Opened 2024-04-16 21:49 UTC by cademirch

### Description

Fixes #2813. `snakemake` and `snakemake-interface-report-plugins` were missing from the req.txt, which are needed to get the argument parser from `snakemake.cli`.

Note: it seems the default report plugin's arguments leak into the docs (see below)
<img width="1018" alt="Screenshot 2024-04-16 at 2 48 53 PM" src="https://github.com/snakemake/snakemake/assets/44762354/ff349a81-0ccc-40d5-99b1-05b959ff1f34">

### QC

* [x] The PR contains a test case for the changes or the changes are already covered by an existing test case.
* [x] The documentation (`docs/`) is updated to reflect the changes or this is not necessary (e.g. if the change does neither modify the language nor the behavior or functionalities of Snakemake).

2024-04-18 19:25 UTC, johanneskoester requested changes

2024-04-18 19:25 UTC, johanneskoester commented on docs/requirements.txt
> +snakemake
```suggestion
```
Snakemake itself is imported from the repo checkout. It should not be needed and I would think it is even harmful here.

2024-04-18 19:38 UTC, cademirch commented
Ah, I figured. I’ll remove it.

Thanks


On Thu, Apr 18, 2024 at 12:26 Johannes Köster ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In docs/requirements.txt
> <https://github.com/snakemake/snakemake/pull/2817#discussion_r1571259069>:
>
> > @@ -7,6 +7,8 @@ configargparse
>  appdirs
>  immutables
>  sphinxawesome-theme
> +snakemake
>
> ⬇️ Suggested change
>
> -snakemake
>
> Snakemake itself is imported from the repo checkout. It should not be
> needed and I would think it is even harmful here.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/snakemake/snakemake/pull/2817#pullrequestreview-2009708907>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AKVQJ4T5AHWL5R2REP4ZMVTY6AM5HAVCNFSM6AAAAABGKEOOJ6VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDAMBZG4YDQOJQG4>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-04-19 06:46 UTC, johanneskoester approved these changes

2024-04-19 06:46 UTC, merged

2024-04-19 06:46 UTC, johanneskoester commented
Thanks a lot!