Updating google_lifesciences.py
snakemake/snakemake pull request #653
Opened 2020-10-01 04:13 UTC by vsoch

We want to update the GLS executor to use the helper script provided in the repository, instead of the one in a gist. The gist is here https://gist.githubusercontent.com/vsoch/f5a6a6d1894be1e67aa4156c5b40c8e9/raw/a4e9ddbeba20996ca62745fcd4d9ecd7bfa3b311/gls.py in case anyone wants to do a comparison!

2020-10-01 11:41 UTC, johanneskoester requested changes
Why not even just distribute the script with Snakemake itself?

2020-10-05 19:59 UTC, johanneskoester commented
I think you are right. I was thinking that, if it is part of the snakemake package, it could be pushed as a file, but that makes little sense, because you need the script to download it then, a hen and egg problem. So, all fine here, thanks.

2020-10-05 20:00 UTC, johanneskoester approved these changes

2020-10-05 20:00 UTC, merged

2020-10-05 20:02 UTC, vsoch commented
:chicken: + :egg: problems!  :) Always hiding in unexpected places. Thanks!