Separate metadata and incomplete job tracking
snakemake/snakemake pull request #663
Opened 2020-10-06 12:51 UTC by mhulsman

Very large numbers of metadata files in the .snakemake/metadata folder can lead to slow performance on network file systems (e.g. Lustre) when checking if jobs are incomplete (--rerun-incomplete). 

1) This code separates the metadata and job-incomplete tracking, by creating an extra .snakemake/incomplete folder.
For the latter, it implements caching, as a simple file existence check suffices to determine if a job is incomplete.  The number of tracking files in the incomplete folder usually remains low, as these are deleted after a job finishes. This results in large speedups when combining --rerun-incomplete with a workflow with many files on a network file system.

Code has been added to enable backwards compatibility with the current .snakemake folder structure.

2) The PR adds also a command line option to make storing of persistent metadata optional to reduce the small file load.

2020-10-09 13:41 UTC, johanneskoester requested changes
Very good idea. I would suggest some slight changes below.

2020-10-09 13:41 UTC, johanneskoester commented on snakemake/__init__.py
> +        help="Drop metadata after job completion.",
Please also mention the missing provenance information this leads to here (for --report, --list-params-changes, etc.).

2020-10-09 13:41 UTC, johanneskoester commented on snakemake/persistence.py
> +            else self._incomplete_path
Why do you store metadata in the incomplete_path?

2020-10-09 13:41 UTC, johanneskoester commented on snakemake/persistence.py
> +        ) and not os.path.exists(self._incomplete_path)
I think if the incomplete folder exists, we can always use the new approach. If it doesn't exist, we can do a one-time migration, by scanning through the metadata path and generating a flag file for each incomplete item in the incomplete path. Then, we can always use the new self.incomplete() version.

2020-10-15 11:53 UTC, johanneskoester approved these changes

2020-10-15 11:53 UTC, merged

2020-10-16 20:50 UTC, mhulsman commented
Also did a quick benchmark of this code, using the same 283k workflow as mentioned in the other pull request, but then not in an empty dir, but one at a point when it is almost complete. Total files will probably be >500k. 

Old: 30985 seconds,   of which 20311 seconds was spent in '_read_record_uncached'. 
New: 776 seconds, of which 21 seconds was spent 'check_incomplete' and 'cache_incomplete_folder'. 

Remaining difference is mostly due to IOCache framework: 
old: 8361 seconds in io.py:wrapper (of which 8271 in 'is_newer')
new:  69 seconds in io.py:wrapper.

2024-10-02 14:03 UTC, hwalinga commented
I think this PR caused #2933

The IncompleteFilesException suggest removing metadata but --cleanup-metadata does not seem to go over the new incomplete folder as well.