add the `name_override` directive to allow names to be programmatical…
snakemake/snakemake pull request #811
Opened 2020-12-18 06:54 UTC by nh13

…ly set

2020-12-18 13:43 UTC, johanneskoester requested changes
brilliant idea! Just one thing.

2020-12-18 13:43 UTC, johanneskoester commented on tests/test_name_override/Snakefile
> +    name_override: some_var
I think I'd just call this `name:`.

2020-12-18 13:43 UTC, johanneskoester commented on snakemake/parser.py
> +class NameOverride(RuleKeywordState):
```suggestion
class Name(RuleKeywordState):
```

2020-12-18 13:43 UTC, johanneskoester commented on snakemake/parser.py
> +        name_override=NameOverride,
```suggestion
        name=NameOverride,
```

2020-12-20 07:17 UTC, nh13 commented on tests/test_name_override/Snakefile
> +    name_override: some_var
Done!

2020-12-20 07:17 UTC, nh13 commented on snakemake/parser.py
> +        name_override=NameOverride,
Done

2020-12-20 07:17 UTC, nh13 commented on snakemake/parser.py
> +class NameOverride(RuleKeywordState):
Done

2020-12-20 07:18 UTC, nh13 commented
@johanneskoester made it work with `name` instead of `name_override` :)

2020-12-21 10:51 UTC, johanneskoester approved these changes

2020-12-21 10:51 UTC, merged

2020-12-21 10:51 UTC, johanneskoester commented
Thank you so much!