Allow params expansion to handle FileNotFoundError (fixes #927)
snakemake/snakemake pull request #932
Opened 2021-03-23 19:41 UTC by ASLeonard

Previously a param value that depended on input that had not been generated previously would fail. Analogous to how resource expansion occurs, I might expect the param expansion to identify the value depends on input not yet available, and display a <TBD> value.

These changes allow for that features by moving the code which handles this in resource expansion to the more general `apply_input_function`. With the FileNotFoundError handling occurring there, the code in the resource expansion could be simplified. 

This was tested on and passes the minimal reproducible example in #927, but may interfere in unexpected ways with other code.

The output of `snakemake -n -p` for a rule with `shell: echo {params}` now looks something like 
```
echo <TBD>
```

2021-03-31 18:21 UTC, johanneskoester requested changes
This is a good idea. Some comments below.

2021-03-31 18:21 UTC, johanneskoester commented on snakemake/rules.py
> +                value = TBDInt(0)
This should then probably be changed into simply a TBD object instead of an Int. Otherwise, it is a big misleading.

2021-03-31 18:21 UTC, johanneskoester commented on snakemake/rules.py
> +            # Resources can depend on input files. Since expansion can happen during dryrun,
```suggestion
            # Function evaluation can depend on input files. Since expansion can happen during dryrun,
```

2021-03-31 18:21 UTC, johanneskoester commented on snakemake/rules.py
> +            # where input files are not yet present, we need to skip such resources and
```suggestion
            # where input files are not yet present, we need to skip such cases and
```

2021-04-01 11:06 UTC, ASLeonard commented
@johanneskoester, these testing action seems to have gotten stuck in some conda/pip loop on the "Setup Snakemake environment" stage for several hours now with the same repeating message. I don't have the ability to kill the workflow action, but these tests are now just burning CPU time.

```
Warning: you have pip-installed dependencies in your environment file, but you do not list pip itself as one of your conda dependencies.  Conda may not use the correct pip to install your packages, and they may end up in the wrong place.  Please add an explicit pip dependency.  I'm adding one for you, but still nagging you.
```

2021-04-01 15:54 UTC, ASLeonard commented
Not sure if it was just a temporary issue with the CI or what, but the tests passed fine now without getting stuck on the setup.

2021-04-21 23:51 UTC, epruesse commented
ping @johanneskoester - I think this is ready?

2021-05-06 10:59 UTC, ASLeonard commented
Any chance of merging this in soon @johanneskoester?

2021-05-17 08:50 UTC, johanneskoester commented
Sorry for the delay!

2021-05-17 08:53 UTC, johanneskoester approved these changes

2021-05-17 08:53 UTC, merged