Fix wrong conversion of string "False" to boolean True in Paramspace
snakemake/snakemake pull request #948
Opened 2021-04-08 09:59 UTC by kpj

Creating a Paramspace from a dataframe which contains the boolean `False` will erroneously convert `False` to `True` when inferring instance values.

This PR adds a simple fix which checks whether the value is `"False"` and from a boolean column and returns `False`.
While this is not very general, more complicated implementations could lead to unneeded complexity.

2021-04-09 10:59 UTC, johanneskoester commented
Not sure I understand the rationale, why not simply rely on the dataframe to be correct when passed over to paramspace? Ensuring that all values and datatypes are correct is up to the developer who loads the dataframe with `pd.read_csv` isn't it?

2021-04-09 12:35 UTC, kpj commented
> Not sure I understand the rationale, why not simply rely on the dataframe to be correct when passed over to paramspace? Ensuring that all values and datatypes are correct is up to the developer who loads the dataframe with `pd.read_csv` isn't it?

Absolutely! But this is exactly what is not working.

Consider the following Snakefile:
```python
import pandas as pd
from snakemake.utils import Paramspace

paramspace = Paramspace(pd.DataFrame({"A": [True, False]}))


rule all:
    input:
        expand("results/{params}/foo", params=paramspace.instance_patterns),


rule foo:
    output:
        touch(f"results/{paramspace.wildcard_pattern}/foo"),
    params:
        pm=paramspace.instance,
    run:
        if params.pm["A"].all():
            print("TRUE")
        else:
            print("FALSE")
```

One would expect it to print both `TRUE` and `FALSE`. However, it will print `TRUE` twice.

This is because the parameter instances are created from the wildcard argument, i.e. strings.
Consequently, the line `name: pd.Series([value]).astype(self.dataframe.dtypes[name])` will evaluate to `name: pd.Series(['False']).astype(np.dtype('bool'))`, which in turn evaluates to `True` (because only the empty string is `False`).

In fact, I do also not understand why the parameter values are wrapped in `pd.Series`.

2021-04-15 10:51 UTC, johanneskoester commented
Ah, now I get it, thanks!

2021-04-15 11:16 UTC, johanneskoester requested changes
Right, no reason for the series. The [0] is missing.

2021-04-15 11:16 UTC, johanneskoester commented on snakemake/utils.py
> +                return pd.Series([False])
```suggestion
                return False
```

2021-04-15 11:16 UTC, johanneskoester commented on snakemake/utils.py
> +                return pd.Series([value]).astype(self.dataframe.dtypes[name])
```suggestion
                return pd.Series([value]).astype(self.dataframe.dtypes[name])[0]
```

2021-04-20 13:34 UTC, johanneskoester approved these changes

2021-04-20 14:52 UTC, merged